spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/defult