eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/defult

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/inventory-service
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 0